version: "3.8"
services:
  osticket:
    image: larueli/osticket-nonroot:v1.15
    restart: always
    ports: 
        - "8080:8080"
    depends_on:
        - osticket_db
    environment:
      - IS_INSTALLED=yes
      - NEEDS_PATCH_REGISTER=yes
    volumes:
      - ./ost-config.php:/var/www/html/include/ost-config.php
      - ./.htaccess:/var/www/html/.htaccess
      - ./attachments:/var/www/html/attachments

  osticket_db:
    image: mariadb:10
    restart: always
    environment:
        - MYSQL_PASSWORD=abcdef
        - MYSQL_DATABASE=osticket
        - MYSQL_USER=osticket
        - MYSQL_ROOT_PASSWORD=kjhgdfizgef
    volumes:
      - ./db-data:/var/lib/mysql

  adminer:
    image: adminer
    #ports:
    #- "8000:8080"
    environment:
      - ADMINER_DESIGN=lucas-sandery
