version: "3.8"
services:
  application:
    image: larueli/osticket-nonroot:v1.16
    restart: always
    ports:
        - "8000:8080"
    depends_on:
        - database
    environment:
      - IS_INSTALLED=yes
    volumes:
      - ./ost-config.php:/var/www/html/include/ost-config.php
      - ./.htaccess:/var/www/html/.htaccess
      - ./attachments:/var/www/html/attachments

  database:
    image: mariadb:10.6
    restart: always
    environment:
        - MYSQL_PASSWORD=abcdef
        - MYSQL_DATABASE=osticket
        - MYSQL_USER=osticket
        - MYSQL_ROOT_PASSWORD=kjhgdfizgef
    volumes:
      - ./db-data:/var/lib/mysql

  adminer:
    image: adminer
    #ports:
    #- "8080:8080"
    environment:
      - ADMINER_DESIGN=lucas-sandery
